# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adjustmentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 454)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout_2.addLayout(self.plotLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 0, 1, 1)
        self.tabLayout = QtWidgets.QVBoxLayout()
        self.tabLayout.setObjectName("tabLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPoles = QtWidgets.QWidget()
        self.tabPoles.setObjectName("tabPoles")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabPoles)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tabPoles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridStueAdd = QtWidgets.QGridLayout()
        self.gridStueAdd.setVerticalSpacing(6)
        self.gridStueAdd.setObjectName("gridStueAdd")
        self.Icons = QtWidgets.QLabel(self.tabPoles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Icons.sizePolicy().hasHeightForWidth())
        self.Icons.setSizePolicy(sizePolicy)
        self.Icons.setMinimumSize(QtCore.QSize(0, 25))
        self.Icons.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Icons.setObjectName("Icons")
        self.gridStueAdd.addWidget(self.Icons, 0, 0, 1, 1)
        self.btnAddPole = QtWidgets.QPushButton(self.tabPoles)
        self.btnAddPole.setMaximumSize(QtCore.QSize(27, 27))
        self.btnAddPole.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddPole.setIcon(icon)
        self.btnAddPole.setObjectName("btnAddPole")
        self.gridStueAdd.addWidget(self.btnAddPole, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridStueAdd)
        self.gridPoles = QtWidgets.QGridLayout()
        self.gridPoles.setVerticalSpacing(6)
        self.gridPoles.setObjectName("gridPoles")
        self.label_19 = QtWidgets.QLabel(self.tabPoles)
        self.label_19.setObjectName("label_19")
        self.gridPoles.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tabPoles)
        self.label_20.setObjectName("label_20")
        self.gridPoles.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tabPoles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 25))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_18.setObjectName("label_18")
        self.gridPoles.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tabPoles)
        self.label_21.setObjectName("label_21")
        self.gridPoles.addWidget(self.label_21, 0, 3, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridPoles)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.tabWidget.addTab(self.tabPoles, "")
        self.tabCableline = QtWidgets.QWidget()
        self.tabCableline.setObjectName("tabCableline")
        self.gridLayout = QtWidgets.QGridLayout(self.tabCableline)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tabCableline)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.tabCableline)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tabCableline)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tabCableline)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tabCableline)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tabCableline)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tabCableline)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tabCableline)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tabCableline)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tabCableline)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tabCableline)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tabCableline)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.fieldQ = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldQ.sizePolicy().hasHeightForWidth())
        self.fieldQ.setSizePolicy(sizePolicy)
        self.fieldQ.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldQ.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldQ.setObjectName("fieldQ")
        self.gridLayout_3.addWidget(self.fieldQ, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tabCableline)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabCableline)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tabCableline)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 3, 1, 1)
        self.fieldQt = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldQt.sizePolicy().hasHeightForWidth())
        self.fieldQt.setSizePolicy(sizePolicy)
        self.fieldQt.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldQt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldQt.setObjectName("fieldQt")
        self.gridLayout_3.addWidget(self.fieldQt, 1, 1, 1, 1)
        self.fieldA = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA.sizePolicy().hasHeightForWidth())
        self.fieldA.setSizePolicy(sizePolicy)
        self.fieldA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldA.setObjectName("fieldA")
        self.gridLayout_3.addWidget(self.fieldA, 2, 1, 1, 1)
        self.fieldE = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE.sizePolicy().hasHeightForWidth())
        self.fieldE.setSizePolicy(sizePolicy)
        self.fieldE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldE.setObjectName("fieldE")
        self.gridLayout_3.addWidget(self.fieldE, 3, 1, 1, 1)
        self.fieldqz1 = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldqz1.sizePolicy().hasHeightForWidth())
        self.fieldqz1.setSizePolicy(sizePolicy)
        self.fieldqz1.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldqz1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldqz1.setObjectName("fieldqz1")
        self.gridLayout_3.addWidget(self.fieldqz1, 4, 1, 1, 1)
        self.fieldqz2 = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldqz2.sizePolicy().hasHeightForWidth())
        self.fieldqz2.setSizePolicy(sizePolicy)
        self.fieldqz2.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldqz2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldqz2.setObjectName("fieldqz2")
        self.gridLayout_3.addWidget(self.fieldqz2, 5, 1, 1, 1)
        self.fieldVorsp = QtWidgets.QLineEdit(self.tabCableline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldVorsp.sizePolicy().hasHeightForWidth())
        self.fieldVorsp.setSizePolicy(sizePolicy)
        self.fieldVorsp.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldVorsp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldVorsp.setObjectName("fieldVorsp")
        self.gridLayout_3.addWidget(self.fieldVorsp, 6, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabCableline, "")
        self.tabThreshold = QtWidgets.QWidget()
        self.tabThreshold.setObjectName("tabThreshold")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabThreshold)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 3, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.tabThreshold)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_29 = QtWidgets.QLabel(self.tabThreshold)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_8.addWidget(self.label_29)
        self.label_34 = QtWidgets.QLabel(self.tabThreshold)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_8.addWidget(self.label_34)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 3, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_39 = QtWidgets.QLabel(self.tabThreshold)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.tabThreshold)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_9.addWidget(self.label_40)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 4, 0, 1, 1)
        self.txtBodenabstT = QtWidgets.QLabel(self.tabThreshold)
        self.txtBodenabstT.setText("")
        self.txtBodenabstT.setObjectName("txtBodenabstT")
        self.gridLayout_5.addWidget(self.txtBodenabstT, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tabThreshold)
        self.label_23.setMinimumSize(QtCore.QSize(0, 30))
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 0, 1, 1)
        self.txtAlphaT = QtWidgets.QLabel(self.tabThreshold)
        self.txtAlphaT.setText("")
        self.txtAlphaT.setObjectName("txtAlphaT")
        self.gridLayout_5.addWidget(self.txtAlphaT, 4, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_41 = QtWidgets.QLabel(self.tabThreshold)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_10.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.tabThreshold)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_10.addWidget(self.label_42)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 5, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tabThreshold)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_32 = QtWidgets.QLabel(self.tabThreshold)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.tabThreshold)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_7.addWidget(self.label_33)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.txtTmaxT = QtWidgets.QLabel(self.tabThreshold)
        self.txtTmaxT.setText("")
        self.txtTmaxT.setObjectName("txtTmaxT")
        self.gridLayout_5.addWidget(self.txtTmaxT, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tabThreshold)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 1, 1, 1)
        self.txtNachwT = QtWidgets.QLabel(self.tabThreshold)
        self.txtNachwT.setText("")
        self.txtNachwT.setObjectName("txtNachwT")
        self.gridLayout_5.addWidget(self.txtNachwT, 5, 1, 1, 1)
        self.txtTmaxV = QtWidgets.QLabel(self.tabThreshold)
        self.txtTmaxV.setText("")
        self.txtTmaxV.setObjectName("txtTmaxV")
        self.gridLayout_5.addWidget(self.txtTmaxV, 2, 2, 1, 1)
        self.txtFSaBefV = QtWidgets.QLabel(self.tabThreshold)
        self.txtFSaBefV.setText("")
        self.txtFSaBefV.setObjectName("txtFSaBefV")
        self.gridLayout_5.addWidget(self.txtFSaBefV, 3, 2, 1, 1)
        self.txtMinBodenabstV = QtWidgets.QLabel(self.tabThreshold)
        self.txtMinBodenabstV.setText("")
        self.txtMinBodenabstV.setObjectName("txtMinBodenabstV")
        self.gridLayout_5.addWidget(self.txtMinBodenabstV, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tabThreshold)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 1, 0, 1, 1)
        self.txtFSaBefT = QtWidgets.QLabel(self.tabThreshold)
        self.txtFSaBefT.setText("")
        self.txtFSaBefT.setObjectName("txtFSaBefT")
        self.gridLayout_5.addWidget(self.txtFSaBefT, 3, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tabThreshold)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 1, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tabThreshold)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 2, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tabThreshold)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 3, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tabThreshold)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 4, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tabThreshold)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 5, 3, 1, 1)
        self.txtAlphaV = QtWidgets.QLabel(self.tabThreshold)
        self.txtAlphaV.setText("")
        self.txtAlphaV.setObjectName("txtAlphaV")
        self.gridLayout_5.addWidget(self.txtAlphaV, 4, 2, 1, 1)
        self.txtNachwV = QtWidgets.QLabel(self.tabThreshold)
        self.txtNachwV.setText("")
        self.txtNachwV.setObjectName("txtNachwV")
        self.gridLayout_5.addWidget(self.txtNachwV, 5, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabThreshold, "")
        self.tabThreshold2 = QtWidgets.QWidget()
        self.tabThreshold2.setObjectName("tabThreshold2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabThreshold2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tableThresholds = QtWidgets.QTableWidget(self.tabThreshold2)
        self.tableThresholds.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableThresholds.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableThresholds.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableThresholds.setRowCount(5)
        self.tableThresholds.setColumnCount(4)
        self.tableThresholds.setObjectName("tableThresholds")
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableThresholds.setItem(4, 0, item)
        self.tableThresholds.horizontalHeader().setVisible(False)
        self.tableThresholds.horizontalHeader().setHighlightSections(True)
        self.tableThresholds.verticalHeader().setVisible(False)
        self.tableThresholds.verticalHeader().setHighlightSections(True)
        self.verticalLayout_11.addWidget(self.tableThresholds)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tabThreshold2, "")
        self.tabComment = QtWidgets.QWidget()
        self.tabComment.setObjectName("tabComment")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabComment)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.tabComment)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.fieldComment = QtWidgets.QPlainTextEdit(self.tabComment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldComment.sizePolicy().hasHeightForWidth())
        self.fieldComment.setSizePolicy(sizePolicy)
        self.fieldComment.setMaximumSize(QtCore.QSize(16777215, 120))
        self.fieldComment.setObjectName("fieldComment")
        self.verticalLayout_3.addWidget(self.fieldComment)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabComment, "")
        self.tabLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.tabLayout, 2, 0, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnBackToStart = QtWidgets.QPushButton(Dialog)
        self.btnBackToStart.setObjectName("btnBackToStart")
        self.buttonLayout.addWidget(self.btnBackToStart)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem7)
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setObjectName("btnSave")
        self.buttonLayout.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.buttonLayout.addWidget(self.btnCancel)
        self.gridLayout_2.addLayout(self.buttonLayout, 7, 0, 1, 1)
        self.calculateLayout = QtWidgets.QHBoxLayout()
        self.calculateLayout.setObjectName("calculateLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.calculateLayout.addItem(spacerItem8)
        self.btnRunCalc = QtWidgets.QPushButton(Dialog)
        self.btnRunCalc.setObjectName("btnRunCalc")
        self.calculateLayout.addWidget(self.btnRunCalc)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.calculateLayout.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.calculateLayout, 4, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem10, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "Feinjustierung der Stützen"))
        self.Icons.setText(_translate("Dialog", "Ico"))
        self.label_19.setText(_translate("Dialog", "Horiz.distanz"))
        self.label_20.setText(_translate("Dialog", "Höhe"))
        self.label_18.setText(_translate("Dialog", "Stütze"))
        self.label_21.setText(_translate("Dialog", "Neigung"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPoles), _translate("Dialog", "Stützen"))
        self.label.setText(_translate("Dialog", "Anpassung der mechanischen Eigenschaften des Tragesystems"))
        self.label_10.setText(_translate("Dialog", "Vorspannung Tragseil"))
        self.label_6.setText(_translate("Dialog", "Querschnittsfläche Tragseil"))
        self.label_2.setText(_translate("Dialog", "Gewicht der Last inkl. Laufwagen"))
        self.label_7.setText(_translate("Dialog", "Elastizitätsmodul Tragseil"))
        self.label_9.setText(_translate("Dialog", "Gewicht des Zugseils rechts"))
        self.label_12.setText(_translate("Dialog", "kN/mm2"))
        self.label_3.setText(_translate("Dialog", "kN"))
        self.label_13.setText(_translate("Dialog", "kN/m"))
        self.label_14.setText(_translate("Dialog", "kN/m"))
        self.label_11.setText(_translate("Dialog", "mm2"))
        self.label_8.setText(_translate("Dialog", "Gewicht des Zugseils links"))
        self.label_5.setText(_translate("Dialog", "kN/m"))
        self.label_4.setText(_translate("Dialog", "Gewicht Tragseil"))
        self.label_15.setText(_translate("Dialog", "kN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCableline), _translate("Dialog", "Tragesystem"))
        self.label_22.setText(_translate("Dialog", "Technische Kennwerte der berechneten Seillinie"))
        self.label_29.setText(_translate("Dialog", "Max. resultierende Sattelkraft"))
        self.label_34.setText(_translate("Dialog", "an befahrbarer Stütze, Last auf Stütze"))
        self.label_39.setText(_translate("Dialog", "Seilwinkel am Lastseil"))
        self.label_40.setText(_translate("Dialog", "(optimaler Bereich 0° - 30°)"))
        self.label_23.setText(_translate("Dialog", "Kennwert"))
        self.label_41.setText(_translate("Dialog", "Nachweis erbracht"))
        self.label_42.setText(_translate("Dialog", "Seil hebt nicht von Sattel ab"))
        self.label_25.setText(_translate("Dialog", "aktuelle Seillinie"))
        self.label_32.setText(_translate("Dialog", "Max. auftretende Seilzugkraft"))
        self.label_33.setText(_translate("Dialog", "Last in Feldmitte des längsten Seilfelds"))
        self.label_24.setText(_translate("Dialog", "Definierter Grenzwert"))
        self.label_26.setText(_translate("Dialog", "Minimaler Bodenabstand"))
        self.label_43.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.label_44.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.label_45.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.label_46.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.label_47.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThreshold), _translate("Dialog", "Kennwerte"))
        item = self.tableThresholds.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableThresholds.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableThresholds.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableThresholds.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableThresholds.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "New Row"))
        item = self.tableThresholds.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Kennwert"))
        item = self.tableThresholds.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Def. Grenzwert"))
        item = self.tableThresholds.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "aktuelle Seillinie"))
        __sortingEnabled = self.tableThresholds.isSortingEnabled()
        self.tableThresholds.setSortingEnabled(False)
        item = self.tableThresholds.item(0, 0)
        item.setText(_translate("Dialog", "Minimaler Bodenabstand"))
        item = self.tableThresholds.item(1, 0)
        item.setText(_translate("Dialog", "Max. auftretende Seilzugkraft am Lastseil (Last in Feldmitte des längsten Seilfeldes)"))
        item = self.tableThresholds.item(2, 0)
        item.setText(_translate("Dialog", "Resultierende Sattelkraft (an befahrbarer Stütze, Last auf Stütze)"))
        item = self.tableThresholds.item(3, 0)
        item.setText(_translate("Dialog", "Seilwinkel am Lastseil (optimaler Bereich 0° - 30°)"))
        item = self.tableThresholds.item(4, 0)
        item.setText(_translate("Dialog", "Nachweis erbracht, dass Seil nicht vom Sattel abhebt"))
        self.tableThresholds.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThreshold2), _translate("Dialog", "Kennwerte2"))
        self.label_16.setText(_translate("Dialog", "Bemerkungstext, welcher im technischen Bericht ergänzt wird"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComment), _translate("Dialog", "Bemerkungen"))
        self.btnBackToStart.setText(_translate("Dialog", "zurück zum Startfenster"))
        self.btnSave.setText(_translate("Dialog", "Ergebnisse speichern"))
        self.btnCancel.setText(_translate("Dialog", "Abbrechen"))
        self.btnRunCalc.setText(_translate("Dialog", "Seillinie neu berechnen"))


from . import resources_rc
