# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seilaplanDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeilaplanDialog(object):
    def setupUi(self, SeilaplanDialog):
        SeilaplanDialog.setObjectName("SeilaplanDialog")
        SeilaplanDialog.resize(575, 912)
        SeilaplanDialog.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SeilaplanDialog.setWindowIcon(icon)
        self.gridLayout_4 = QtWidgets.QGridLayout(SeilaplanDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(SeilaplanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.radioRaster = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioRaster.setObjectName("radioRaster")
        self.gridLayout_15.addWidget(self.radioRaster, 0, 0, 1, 1)
        self.radioSurveyData = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioSurveyData.setObjectName("radioSurveyData")
        self.gridLayout_15.addWidget(self.radioSurveyData, 1, 0, 1, 1)
        self.buttonRefreshRa = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRefreshRa.sizePolicy().hasHeightForWidth())
        self.buttonRefreshRa.setSizePolicy(sizePolicy)
        self.buttonRefreshRa.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonRefreshRa.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRefreshRa.setIcon(icon1)
        self.buttonRefreshRa.setIconSize(QtCore.QSize(24, 24))
        self.buttonRefreshRa.setAutoDefault(False)
        self.buttonRefreshRa.setObjectName("buttonRefreshRa")
        self.gridLayout_15.addWidget(self.buttonRefreshRa, 0, 3, 1, 1)
        self.fieldSurveyDataPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.fieldSurveyDataPath.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.fieldSurveyDataPath.setFont(font)
        self.fieldSurveyDataPath.setStyleSheet("color: rgb(136, 138, 133);")
        self.fieldSurveyDataPath.setReadOnly(True)
        self.fieldSurveyDataPath.setObjectName("fieldSurveyDataPath")
        self.gridLayout_15.addWidget(self.fieldSurveyDataPath, 1, 2, 1, 1)
        self.rasterField = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rasterField.sizePolicy().hasHeightForWidth())
        self.rasterField.setSizePolicy(sizePolicy)
        self.rasterField.setMinimumSize(QtCore.QSize(220, 0))
        self.rasterField.setObjectName("rasterField")
        self.gridLayout_15.addWidget(self.rasterField, 0, 2, 1, 1)
        self.buttonLoadSurveyData = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonLoadSurveyData.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonLoadSurveyData.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLoadSurveyData.setIcon(icon2)
        self.buttonLoadSurveyData.setIconSize(QtCore.QSize(24, 24))
        self.buttonLoadSurveyData.setObjectName("buttonLoadSurveyData")
        self.gridLayout_15.addWidget(self.buttonLoadSurveyData, 1, 3, 1, 1)
        self.infoSurveyData = QtWidgets.QPushButton(self.groupBox_2)
        self.infoSurveyData.setMaximumSize(QtCore.QSize(22, 22))
        self.infoSurveyData.setObjectName("infoSurveyData")
        self.gridLayout_15.addWidget(self.infoSurveyData, 1, 4, 1, 1)
        self.infoRasterlayer = QtWidgets.QPushButton(self.groupBox_2)
        self.infoRasterlayer.setMaximumSize(QtCore.QSize(22, 22))
        self.infoRasterlayer.setObjectName("infoRasterlayer")
        self.gridLayout_15.addWidget(self.infoRasterlayer, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_15)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(SeilaplanDialog)
        self.groupBox_5.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.fieldProjName = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldProjName.sizePolicy().hasHeightForWidth())
        self.fieldProjName.setSizePolicy(sizePolicy)
        self.fieldProjName.setMinimumSize(QtCore.QSize(305, 0))
        self.fieldProjName.setObjectName("fieldProjName")
        self.gridLayout.addWidget(self.fieldProjName, 0, 2, 1, 1)
        self.buttonSavePr = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSavePr.sizePolicy().hasHeightForWidth())
        self.buttonSavePr.setSizePolicy(sizePolicy)
        self.buttonSavePr.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonSavePr.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSavePr.setIcon(icon3)
        self.buttonSavePr.setIconSize(QtCore.QSize(24, 24))
        self.buttonSavePr.setAutoDefault(False)
        self.buttonSavePr.setObjectName("buttonSavePr")
        self.gridLayout.addWidget(self.buttonSavePr, 0, 4, 1, 1)
        self.buttonOpenPr = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOpenPr.sizePolicy().hasHeightForWidth())
        self.buttonOpenPr.setSizePolicy(sizePolicy)
        self.buttonOpenPr.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonOpenPr.setText("")
        self.buttonOpenPr.setIcon(icon2)
        self.buttonOpenPr.setIconSize(QtCore.QSize(24, 24))
        self.buttonOpenPr.setAutoDefault(False)
        self.buttonOpenPr.setObjectName("buttonOpenPr")
        self.gridLayout.addWidget(self.buttonOpenPr, 0, 5, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(SeilaplanDialog)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.fieldParamSet = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldParamSet.sizePolicy().hasHeightForWidth())
        self.fieldParamSet.setSizePolicy(sizePolicy)
        self.fieldParamSet.setMinimumSize(QtCore.QSize(220, 0))
        self.fieldParamSet.setObjectName("fieldParamSet")
        self.horizontalLayout_13.addWidget(self.fieldParamSet)
        self.buttonSaveParamset = QtWidgets.QPushButton(self.groupBox)
        self.buttonSaveParamset.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonSaveParamset.setText("")
        self.buttonSaveParamset.setIcon(icon3)
        self.buttonSaveParamset.setIconSize(QtCore.QSize(24, 24))
        self.buttonSaveParamset.setAutoDefault(False)
        self.buttonSaveParamset.setObjectName("buttonSaveParamset")
        self.horizontalLayout_13.addWidget(self.buttonSaveParamset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_5.sizePolicy().hasHeightForWidth())
        self.tab_5.setSizePolicy(sizePolicy)
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_54 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_2.addWidget(self.label_54)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.fieldA = QtWidgets.QLineEdit(self.tab_5)
        self.fieldA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldA.setObjectName("fieldA")
        self.gridLayout_8.addWidget(self.fieldA, 3, 1, 1, 1)
        self.fieldqz2 = QtWidgets.QLineEdit(self.tab_5)
        self.fieldqz2.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldqz2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldqz2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldqz2.setObjectName("fieldqz2")
        self.gridLayout_8.addWidget(self.fieldqz2, 8, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(40, 0))
        self.label_36.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 7, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 4, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setMinimumSize(QtCore.QSize(40, 0))
        self.label_47.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 6, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 8, 0, 1, 1)
        self.fieldQt = QtWidgets.QLineEdit(self.tab_5)
        self.fieldQt.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldQt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldQt.setObjectName("fieldQt")
        self.gridLayout_8.addWidget(self.fieldQt, 2, 1, 1, 1)
        self.fieldQ = QtWidgets.QLineEdit(self.tab_5)
        self.fieldQ.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldQ.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldQ.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldQ.setObjectName("fieldQ")
        self.gridLayout_8.addWidget(self.fieldQ, 1, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_5)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 6, 0, 1, 1)
        self.fieldE = QtWidgets.QLineEdit(self.tab_5)
        self.fieldE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldE.setObjectName("fieldE")
        self.gridLayout_8.addWidget(self.fieldE, 4, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 5, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(40, 0))
        self.label_49.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 2, 2, 1, 1)
        self.fieldminSK = QtWidgets.QLineEdit(self.tab_5)
        self.fieldminSK.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldminSK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldminSK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldminSK.setObjectName("fieldminSK")
        self.gridLayout_8.addWidget(self.fieldminSK, 6, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(40, 0))
        self.label_45.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 5, 2, 1, 1)
        self.fieldqz1 = QtWidgets.QLineEdit(self.tab_5)
        self.fieldqz1.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldqz1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldqz1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldqz1.setObjectName("fieldqz1")
        self.gridLayout_8.addWidget(self.fieldqz1, 7, 1, 1, 1)
        self.fieldzulSK = QtWidgets.QLineEdit(self.tab_5)
        self.fieldzulSK.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldzulSK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldzulSK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldzulSK.setObjectName("fieldzulSK")
        self.gridLayout_8.addWidget(self.fieldzulSK, 5, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setMinimumSize(QtCore.QSize(40, 0))
        self.label_46.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 8, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(40, 0))
        self.label_44.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setMinimumSize(QtCore.QSize(40, 0))
        self.label_52.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_52.setObjectName("label_52")
        self.gridLayout_8.addWidget(self.label_52, 4, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 7, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setMinimumSize(QtCore.QSize(40, 0))
        self.label_51.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 3, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem3, 5, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.gridLayout_12.addWidget(self.label_58, 2, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName("label_62")
        self.gridLayout_11.addWidget(self.label_62, 0, 0, 1, 1)
        self.fieldBabstMin = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBabstMin.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBabstMin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBabstMin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBabstMin.setObjectName("fieldBabstMin")
        self.gridLayout_11.addWidget(self.fieldBabstMin, 0, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setMinimumSize(QtCore.QSize(24, 0))
        self.label_60.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_60.setObjectName("label_60")
        self.gridLayout_11.addWidget(self.label_60, 0, 2, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName("label_61")
        self.gridLayout_11.addWidget(self.label_61, 1, 0, 1, 1)
        self.fieldBabstA = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBabstA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBabstA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBabstA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBabstA.setObjectName("fieldBabstA")
        self.gridLayout_11.addWidget(self.fieldBabstA, 1, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(24, 0))
        self.label_64.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_64.setObjectName("label_64")
        self.gridLayout_11.addWidget(self.label_64, 1, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 2, 0, 1, 1)
        self.fieldBabstE = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBabstE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBabstE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBabstE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBabstE.setObjectName("fieldBabstE")
        self.gridLayout_11.addWidget(self.fieldBabstE, 2, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(24, 0))
        self.label_57.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_57.setObjectName("label_57")
        self.gridLayout_11.addWidget(self.label_57, 2, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 1, 0, 1, 3)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        self.label_65.setObjectName("label_65")
        self.gridLayout_10.addWidget(self.label_65, 1, 0, 1, 1)
        self.fieldBefA = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBefA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBefA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBefA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBefA.setObjectName("fieldBefA")
        self.gridLayout_10.addWidget(self.fieldBefA, 1, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setMinimumSize(QtCore.QSize(24, 0))
        self.label_59.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_59.setObjectName("label_59")
        self.gridLayout_10.addWidget(self.label_59, 1, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.tab_3)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 2, 0, 1, 1)
        self.fieldBefE = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBefE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBefE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBefE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBefE.setObjectName("fieldBefE")
        self.gridLayout_10.addWidget(self.fieldBefE, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setMinimumSize(QtCore.QSize(24, 0))
        self.label_56.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_56.setObjectName("label_56")
        self.gridLayout_10.addWidget(self.label_56, 2, 2, 1, 1)
        self.fieldGravSK = QtWidgets.QComboBox(self.tab_3)
        self.fieldGravSK.setObjectName("fieldGravSK")
        self.fieldGravSK.addItem("")
        self.fieldGravSK.addItem("")
        self.gridLayout_10.addWidget(self.fieldGravSK, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 4, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 2, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_67 = QtWidgets.QLabel(self.tab_3)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_6.addWidget(self.label_67)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 3, 0, 1, 3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_66 = QtWidgets.QLabel(self.tab_3)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_5.addWidget(self.label_66)
        self.infoBodenabstand = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBodenabstand.sizePolicy().hasHeightForWidth())
        self.infoBodenabstand.setSizePolicy(sizePolicy)
        self.infoBodenabstand.setMinimumSize(QtCore.QSize(0, 0))
        self.infoBodenabstand.setMaximumSize(QtCore.QSize(22, 22))
        self.infoBodenabstand.setAutoDefault(False)
        self.infoBodenabstand.setObjectName("infoBodenabstand")
        self.horizontalLayout_5.addWidget(self.infoBodenabstand)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_12.addLayout(self.horizontalLayout_5, 0, 0, 1, 3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.infoVerankerungA = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoVerankerungA.sizePolicy().hasHeightForWidth())
        self.infoVerankerungA.setSizePolicy(sizePolicy)
        self.infoVerankerungA.setMinimumSize(QtCore.QSize(0, 0))
        self.infoVerankerungA.setMaximumSize(QtCore.QSize(22, 22))
        self.infoVerankerungA.setAutoDefault(False)
        self.infoVerankerungA.setObjectName("infoVerankerungA")
        self.horizontalLayout_7.addWidget(self.infoVerankerungA)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_14.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_76 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setMinimumSize(QtCore.QSize(216, 0))
        self.label_76.setObjectName("label_76")
        self.gridLayout_7.addWidget(self.label_76, 0, 0, 1, 1)
        self.fieldHManf = QtWidgets.QLineEdit(self.tab_2)
        self.fieldHManf.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHManf.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHManf.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHManf.setObjectName("fieldHManf")
        self.gridLayout_7.addWidget(self.fieldHManf, 0, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setMinimumSize(QtCore.QSize(24, 0))
        self.label_77.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_77.setObjectName("label_77")
        self.gridLayout_7.addWidget(self.label_77, 0, 2, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setMinimumSize(QtCore.QSize(216, 0))
        self.label_78.setObjectName("label_78")
        self.gridLayout_7.addWidget(self.label_78, 1, 0, 1, 1)
        self.fieldDAnkA = QtWidgets.QLineEdit(self.tab_2)
        self.fieldDAnkA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldDAnkA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldDAnkA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldDAnkA.setObjectName("fieldDAnkA")
        self.gridLayout_7.addWidget(self.fieldDAnkA, 1, 1, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_79.sizePolicy().hasHeightForWidth())
        self.label_79.setSizePolicy(sizePolicy)
        self.label_79.setMinimumSize(QtCore.QSize(24, 0))
        self.label_79.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_79.setObjectName("label_79")
        self.gridLayout_7.addWidget(self.label_79, 1, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem8, 2, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.infoVerankerungE = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoVerankerungE.sizePolicy().hasHeightForWidth())
        self.infoVerankerungE.setSizePolicy(sizePolicy)
        self.infoVerankerungE.setMinimumSize(QtCore.QSize(0, 0))
        self.infoVerankerungE.setMaximumSize(QtCore.QSize(22, 22))
        self.infoVerankerungE.setAutoDefault(False)
        self.infoVerankerungE.setObjectName("infoVerankerungE")
        self.horizontalLayout_9.addWidget(self.infoVerankerungE)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.gridLayout_14.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem10, 5, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_80 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_80.sizePolicy().hasHeightForWidth())
        self.label_80.setSizePolicy(sizePolicy)
        self.label_80.setMinimumSize(QtCore.QSize(216, 0))
        self.label_80.setObjectName("label_80")
        self.gridLayout_13.addWidget(self.label_80, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fieldHMeMin = QtWidgets.QLineEdit(self.tab_2)
        self.fieldHMeMin.setMinimumSize(QtCore.QSize(40, 0))
        self.fieldHMeMin.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fieldHMeMin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMeMin.setObjectName("fieldHMeMin")
        self.horizontalLayout_8.addWidget(self.fieldHMeMin)
        self.fieldHMeMax = QtWidgets.QLineEdit(self.tab_2)
        self.fieldHMeMax.setMinimumSize(QtCore.QSize(40, 0))
        self.fieldHMeMax.setMaximumSize(QtCore.QSize(40, 16777215))
        self.fieldHMeMax.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMeMax.setObjectName("fieldHMeMax")
        self.horizontalLayout_8.addWidget(self.fieldHMeMax)
        self.gridLayout_13.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_81.sizePolicy().hasHeightForWidth())
        self.label_81.setSizePolicy(sizePolicy)
        self.label_81.setMinimumSize(QtCore.QSize(24, 0))
        self.label_81.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_81.setObjectName("label_81")
        self.gridLayout_13.addWidget(self.label_81, 1, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_82.sizePolicy().hasHeightForWidth())
        self.label_82.setSizePolicy(sizePolicy)
        self.label_82.setMinimumSize(QtCore.QSize(216, 0))
        self.label_82.setObjectName("label_82")
        self.gridLayout_13.addWidget(self.label_82, 2, 0, 1, 1)
        self.fieldDAnkE = QtWidgets.QLineEdit(self.tab_2)
        self.fieldDAnkE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldDAnkE.setMaximumSize(QtCore.QSize(90, 16777215))
        self.fieldDAnkE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldDAnkE.setObjectName("fieldDAnkE")
        self.gridLayout_13.addWidget(self.fieldDAnkE, 2, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_83.sizePolicy().hasHeightForWidth())
        self.label_83.setSizePolicy(sizePolicy)
        self.label_83.setMinimumSize(QtCore.QSize(24, 0))
        self.label_83.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_83.setObjectName("label_83")
        self.gridLayout_13.addWidget(self.label_83, 2, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.gridLayout_13.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_68 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setMinimumSize(QtCore.QSize(275, 0))
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 0, 0, 1, 1)
        self.fieldMinDist = QtWidgets.QLineEdit(self.tab)
        self.fieldMinDist.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldMinDist.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldMinDist.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldMinDist.setObjectName("fieldMinDist")
        self.gridLayout_3.addWidget(self.fieldMinDist, 0, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_69.sizePolicy().hasHeightForWidth())
        self.label_69.setSizePolicy(sizePolicy)
        self.label_69.setMinimumSize(QtCore.QSize(24, 0))
        self.label_69.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 0, 2, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_70.sizePolicy().hasHeightForWidth())
        self.label_70.setSizePolicy(sizePolicy)
        self.label_70.setMinimumSize(QtCore.QSize(275, 0))
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 1, 0, 1, 1)
        self.fieldLdelta = QtWidgets.QLineEdit(self.tab)
        self.fieldLdelta.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldLdelta.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldLdelta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldLdelta.setObjectName("fieldLdelta")
        self.gridLayout_3.addWidget(self.fieldLdelta, 1, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy)
        self.label_71.setMinimumSize(QtCore.QSize(24, 0))
        self.label_71.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(275, 0))
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.fieldNzwSt = QtWidgets.QLineEdit(self.tab)
        self.fieldNzwSt.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldNzwSt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldNzwSt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldNzwSt.setObjectName("fieldNzwSt")
        self.gridLayout_3.addWidget(self.fieldNzwSt, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem12, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem14, 2, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_72 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setMinimumSize(QtCore.QSize(275, 0))
        self.label_72.setObjectName("label_72")
        self.gridLayout_2.addWidget(self.label_72, 0, 0, 1, 1)
        self.fieldHMmin = QtWidgets.QLineEdit(self.tab)
        self.fieldHMmin.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMmin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMmin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMmin.setObjectName("fieldHMmin")
        self.gridLayout_2.addWidget(self.fieldHMmin, 0, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(24, 0))
        self.label_73.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_73.setObjectName("label_73")
        self.gridLayout_2.addWidget(self.label_73, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(275, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.fieldHMmax = QtWidgets.QLineEdit(self.tab)
        self.fieldHMmax.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMmax.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMmax.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMmax.setObjectName("fieldHMmax")
        self.gridLayout_2.addWidget(self.fieldHMmax, 1, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(24, 0))
        self.label_74.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_74.setObjectName("label_74")
        self.gridLayout_2.addWidget(self.label_74, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMinimumSize(QtCore.QSize(275, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.fieldHMdelta = QtWidgets.QLineEdit(self.tab)
        self.fieldHMdelta.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMdelta.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMdelta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMdelta.setObjectName("fieldHMdelta")
        self.gridLayout_2.addWidget(self.fieldHMdelta, 2, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setMinimumSize(QtCore.QSize(24, 0))
        self.label_75.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_75.setObjectName("label_75")
        self.gridLayout_2.addWidget(self.label_75, 2, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setMinimumSize(QtCore.QSize(275, 0))
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 1)
        self.fieldHMnat = QtWidgets.QLineEdit(self.tab)
        self.fieldHMnat.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMnat.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMnat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMnat.setObjectName("fieldHMnat")
        self.gridLayout_2.addWidget(self.fieldHMnat, 3, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setMinimumSize(QtCore.QSize(24, 0))
        self.label_84.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_84.setObjectName("label_84")
        self.gridLayout_2.addWidget(self.label_84, 3, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        self.infoStuetzen = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoStuetzen.sizePolicy().hasHeightForWidth())
        self.infoStuetzen.setSizePolicy(sizePolicy)
        self.infoStuetzen.setMinimumSize(QtCore.QSize(0, 0))
        self.infoStuetzen.setMaximumSize(QtCore.QSize(22, 22))
        self.infoStuetzen.setAutoDefault(False)
        self.infoStuetzen.setObjectName("infoStuetzen")
        self.gridLayout_6.addWidget(self.infoStuetzen, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(SeilaplanDialog)
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.draw = QtWidgets.QPushButton(self.groupBox_3)
        self.draw.setAutoDefault(False)
        self.draw.setObjectName("draw")
        self.gridLayout_17.addWidget(self.draw, 0, 1, 1, 1)
        self.osmLyrButton = QtWidgets.QPushButton(self.groupBox_3)
        self.osmLyrButton.setMaximumSize(QtCore.QSize(27, 27))
        self.osmLyrButton.setToolTip("OpenStreetMap Layer laden")
        self.osmLyrButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.osmLyrButton.setIcon(icon4)
        self.osmLyrButton.setAutoDefault(False)
        self.osmLyrButton.setObjectName("osmLyrButton")
        self.gridLayout_17.addWidget(self.osmLyrButton, 0, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_17.addWidget(self.label_25, 0, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem15, 0, 3, 1, 1)
        self.contourLyrButton = QtWidgets.QPushButton(self.groupBox_3)
        self.contourLyrButton.setMaximumSize(QtCore.QSize(27, 27))
        self.contourLyrButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_contour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contourLyrButton.setIcon(icon5)
        self.contourLyrButton.setAutoDefault(False)
        self.contourLyrButton.setObjectName("contourLyrButton")
        self.gridLayout_17.addWidget(self.contourLyrButton, 0, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.symA = QtWidgets.QLabel(self.groupBox_3)
        self.symA.setObjectName("symA")
        self.gridLayout_18.addWidget(self.symA, 1, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_18.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_18.addWidget(self.label_28, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_18.addWidget(self.label_29, 1, 1, 1, 1)
        self.coordAy = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordAy.sizePolicy().hasHeightForWidth())
        self.coordAy.setSizePolicy(sizePolicy)
        self.coordAy.setMinimumSize(QtCore.QSize(100, 0))
        self.coordAy.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordAy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordAy.setObjectName("coordAy")
        self.gridLayout_18.addWidget(self.coordAy, 1, 3, 1, 1)
        self.symTxtE = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symTxtE.sizePolicy().hasHeightForWidth())
        self.symTxtE.setSizePolicy(sizePolicy)
        self.symTxtE.setMinimumSize(QtCore.QSize(140, 0))
        self.symTxtE.setObjectName("symTxtE")
        self.gridLayout_18.addWidget(self.symTxtE, 2, 5, 1, 1)
        self.symTxtA = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symTxtA.sizePolicy().hasHeightForWidth())
        self.symTxtA.setSizePolicy(sizePolicy)
        self.symTxtA.setMinimumSize(QtCore.QSize(140, 0))
        self.symTxtA.setObjectName("symTxtA")
        self.gridLayout_18.addWidget(self.symTxtA, 1, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 2, 1, 1, 1)
        self.coordEy = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordEy.sizePolicy().hasHeightForWidth())
        self.coordEy.setSizePolicy(sizePolicy)
        self.coordEy.setMinimumSize(QtCore.QSize(100, 0))
        self.coordEy.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordEy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordEy.setObjectName("coordEy")
        self.gridLayout_18.addWidget(self.coordEy, 2, 3, 1, 1)
        self.symE = QtWidgets.QLabel(self.groupBox_3)
        self.symE.setObjectName("symE")
        self.gridLayout_18.addWidget(self.symE, 2, 4, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem16, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem17, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_18.addWidget(self.label_2, 4, 1, 1, 1)
        self.coordEx = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordEx.sizePolicy().hasHeightForWidth())
        self.coordEx.setSizePolicy(sizePolicy)
        self.coordEx.setMinimumSize(QtCore.QSize(100, 0))
        self.coordEx.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordEx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordEx.setObjectName("coordEx")
        self.gridLayout_18.addWidget(self.coordEx, 2, 2, 1, 1)
        self.coordAx = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordAx.sizePolicy().hasHeightForWidth())
        self.coordAx.setSizePolicy(sizePolicy)
        self.coordAx.setMinimumSize(QtCore.QSize(100, 0))
        self.coordAx.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordAx.setToolTip("")
        self.coordAx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordAx.setObjectName("coordAx")
        self.gridLayout_18.addWidget(self.coordAx, 1, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.laenge = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laenge.sizePolicy().hasHeightForWidth())
        self.laenge.setSizePolicy(sizePolicy)
        self.laenge.setMinimumSize(QtCore.QSize(41, 0))
        self.laenge.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.laenge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laenge.setReadOnly(True)
        self.laenge.setObjectName("laenge")
        self.horizontalLayout_12.addWidget(self.laenge)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.gridLayout_18.addLayout(self.horizontalLayout_12, 4, 2, 1, 1)
        self.buttonShowProf = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonShowProf.setAutoDefault(False)
        self.buttonShowProf.setObjectName("buttonShowProf")
        self.gridLayout_18.addWidget(self.buttonShowProf, 4, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_18, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.buttonInfo = QtWidgets.QPushButton(SeilaplanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInfo.sizePolicy().hasHeightForWidth())
        self.buttonInfo.setSizePolicy(sizePolicy)
        self.buttonInfo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.buttonInfo.setAutoDefault(False)
        self.buttonInfo.setObjectName("buttonInfo")
        self.horizontalLayout_11.addWidget(self.buttonInfo)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.buttonCancel = QtWidgets.QPushButton(SeilaplanDialog)
        self.buttonCancel.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonCancel.setAutoDefault(False)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_11.addWidget(self.buttonCancel)
        self.btnAdjustment = QtWidgets.QPushButton(SeilaplanDialog)
        self.btnAdjustment.setAutoDefault(False)
        self.btnAdjustment.setObjectName("btnAdjustment")
        self.horizontalLayout_11.addWidget(self.btnAdjustment)
        self.buttonRun = QtWidgets.QPushButton(SeilaplanDialog)
        self.buttonRun.setAutoDefault(False)
        self.buttonRun.setObjectName("buttonRun")
        self.horizontalLayout_11.addWidget(self.buttonRun)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)

        self.retranslateUi(SeilaplanDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SeilaplanDialog)
        SeilaplanDialog.setTabOrder(self.fieldProjName, self.buttonSavePr)
        SeilaplanDialog.setTabOrder(self.buttonSavePr, self.buttonOpenPr)
        SeilaplanDialog.setTabOrder(self.buttonOpenPr, self.draw)
        SeilaplanDialog.setTabOrder(self.draw, self.coordAx)
        SeilaplanDialog.setTabOrder(self.coordAx, self.coordAy)
        SeilaplanDialog.setTabOrder(self.coordAy, self.coordEx)
        SeilaplanDialog.setTabOrder(self.coordEx, self.coordEy)
        SeilaplanDialog.setTabOrder(self.coordEy, self.laenge)
        SeilaplanDialog.setTabOrder(self.laenge, self.buttonShowProf)
        SeilaplanDialog.setTabOrder(self.buttonShowProf, self.fieldParamSet)
        SeilaplanDialog.setTabOrder(self.fieldParamSet, self.buttonSaveParamset)
        SeilaplanDialog.setTabOrder(self.buttonSaveParamset, self.tabWidget)
        SeilaplanDialog.setTabOrder(self.tabWidget, self.fieldQ)
        SeilaplanDialog.setTabOrder(self.fieldQ, self.fieldQt)
        SeilaplanDialog.setTabOrder(self.fieldQt, self.fieldA)
        SeilaplanDialog.setTabOrder(self.fieldA, self.fieldE)
        SeilaplanDialog.setTabOrder(self.fieldE, self.fieldzulSK)
        SeilaplanDialog.setTabOrder(self.fieldzulSK, self.fieldminSK)
        SeilaplanDialog.setTabOrder(self.fieldminSK, self.fieldqz1)
        SeilaplanDialog.setTabOrder(self.fieldqz1, self.fieldqz2)
        SeilaplanDialog.setTabOrder(self.fieldqz2, self.fieldBabstMin)
        SeilaplanDialog.setTabOrder(self.fieldBabstMin, self.fieldBabstA)
        SeilaplanDialog.setTabOrder(self.fieldBabstA, self.fieldBabstE)
        SeilaplanDialog.setTabOrder(self.fieldBabstE, self.fieldGravSK)
        SeilaplanDialog.setTabOrder(self.fieldGravSK, self.fieldBefA)
        SeilaplanDialog.setTabOrder(self.fieldBefA, self.fieldBefE)
        SeilaplanDialog.setTabOrder(self.fieldBefE, self.fieldHManf)
        SeilaplanDialog.setTabOrder(self.fieldHManf, self.fieldDAnkA)
        SeilaplanDialog.setTabOrder(self.fieldDAnkA, self.fieldHMeMin)
        SeilaplanDialog.setTabOrder(self.fieldHMeMin, self.fieldHMeMax)
        SeilaplanDialog.setTabOrder(self.fieldHMeMax, self.fieldDAnkE)
        SeilaplanDialog.setTabOrder(self.fieldDAnkE, self.fieldMinDist)
        SeilaplanDialog.setTabOrder(self.fieldMinDist, self.fieldLdelta)
        SeilaplanDialog.setTabOrder(self.fieldLdelta, self.fieldNzwSt)
        SeilaplanDialog.setTabOrder(self.fieldNzwSt, self.fieldHMmin)
        SeilaplanDialog.setTabOrder(self.fieldHMmin, self.fieldHMmax)
        SeilaplanDialog.setTabOrder(self.fieldHMmax, self.fieldHMdelta)
        SeilaplanDialog.setTabOrder(self.fieldHMdelta, self.fieldHMnat)
        SeilaplanDialog.setTabOrder(self.fieldHMnat, self.buttonInfo)
        SeilaplanDialog.setTabOrder(self.buttonInfo, self.buttonCancel)
        SeilaplanDialog.setTabOrder(self.buttonCancel, self.buttonRun)
        SeilaplanDialog.setTabOrder(self.buttonRun, self.infoBodenabstand)
        SeilaplanDialog.setTabOrder(self.infoBodenabstand, self.infoVerankerungA)
        SeilaplanDialog.setTabOrder(self.infoVerankerungA, self.infoVerankerungE)

    def retranslateUi(self, SeilaplanDialog):
        _translate = QtCore.QCoreApplication.translate
        SeilaplanDialog.setWindowTitle(_translate("SeilaplanDialog", "SEILAPLAN - Seilkran-Layoutplaner"))
        self.groupBox_2.setTitle(_translate("SeilaplanDialog", "Höhenmodell"))
        self.radioRaster.setToolTip(_translate("SeilaplanDialog", "Auswahl eines QGIS-Rasterlayer im aktuellen Projekt"))
        self.radioRaster.setText(_translate("SeilaplanDialog", "Rasterlayer"))
        self.radioSurveyData.setToolTip(_translate("SeilaplanDialog", "Höhenprofil aus Feldaufnahmen laden"))
        self.radioSurveyData.setText(_translate("SeilaplanDialog", "Höhenprofil"))
        self.buttonRefreshRa.setToolTip(_translate("SeilaplanDialog", "Liste der in QGIS geladenen Raster aktualisieren"))
        self.fieldSurveyDataPath.setToolTip(_translate("SeilaplanDialog", "Pfad zu csv-Datei"))
        self.buttonLoadSurveyData.setToolTip(_translate("SeilaplanDialog", "Öffne Komma-getrennte Textdatei (.csv Datei)"))
        self.infoSurveyData.setText(_translate("SeilaplanDialog", "?"))
        self.infoRasterlayer.setText(_translate("SeilaplanDialog", "?"))
        self.groupBox_5.setTitle(_translate("SeilaplanDialog", "Projekt"))
        self.label_7.setText(_translate("SeilaplanDialog", "Projektname"))
        self.buttonSavePr.setToolTip(_translate("SeilaplanDialog", "Einstellungen in Textdatei abspeichern"))
        self.buttonOpenPr.setToolTip(_translate("SeilaplanDialog", "Projekteinstellungen aus Textdatei laden"))
        self.groupBox.setTitle(_translate("SeilaplanDialog", "Eigenschaften der Seillinie"))
        self.label_6.setText(_translate("SeilaplanDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Parameterset auswählen</span></p></body></html>"))
        self.buttonSaveParamset.setToolTip(_translate("SeilaplanDialog", "Eigenschaften der Seillinie in neuem Parameterset abspeichern"))
        self.label_54.setText(_translate("SeilaplanDialog", "<b>Mechanische Eigenschaften</b>"))
        self.label_30.setText(_translate("SeilaplanDialog", "Querschnittsfläche Tragseil"))
        self.label_36.setText(_translate("SeilaplanDialog", "kN/m"))
        self.label_42.setText(_translate("SeilaplanDialog", "Elastizitätsmodul Tragseil"))
        self.label_47.setText(_translate("SeilaplanDialog", "kN"))
        self.label_35.setText(_translate("SeilaplanDialog", "Gewicht des Zugseils rechts"))
        self.label_53.setText(_translate("SeilaplanDialog", "Minimal zulässige Seilzugkraft"))
        self.label_50.setText(_translate("SeilaplanDialog", "Gewicht der Last inkl. Laufwagen"))
        self.label_37.setText(_translate("SeilaplanDialog", "Maximal zulässige Seilzugkraft"))
        self.label_49.setText(_translate("SeilaplanDialog", "kN/m"))
        self.label_48.setText(_translate("SeilaplanDialog", "Gewicht Tragseil"))
        self.label_45.setText(_translate("SeilaplanDialog", "kN"))
        self.label_46.setText(_translate("SeilaplanDialog", "kN/m"))
        self.label_44.setText(_translate("SeilaplanDialog", "kN"))
        self.label_52.setText(_translate("SeilaplanDialog", "kN/mm2"))
        self.label_43.setText(_translate("SeilaplanDialog", "Gewicht des Zugseils links"))
        self.label_51.setText(_translate("SeilaplanDialog", "mm2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("SeilaplanDialog", "Tragesystem #1"))
        self.label_62.setText(_translate("SeilaplanDialog", "Minimaler Abstand Tragseil - Boden"))
        self.label_60.setText(_translate("SeilaplanDialog", "m"))
        self.label_61.setText(_translate("SeilaplanDialog", "einzuhalten ab ... vom Anfangspunkt"))
        self.label_64.setText(_translate("SeilaplanDialog", "m"))
        self.label_55.setText(_translate("SeilaplanDialog", "einzuhalten bis ... vor dem Endpunkt"))
        self.label_57.setText(_translate("SeilaplanDialog", "m"))
        self.label_15.setText(_translate("SeilaplanDialog", "Gravitationsseilkran ja/nein?"))
        self.label_65.setText(_translate("SeilaplanDialog", "Befahrbar ab ... vom Anfangspunkt"))
        self.label_59.setText(_translate("SeilaplanDialog", "m"))
        self.label_63.setText(_translate("SeilaplanDialog", "Befahrbar bis ... vor dem Endpunkt   "))
        self.label_56.setText(_translate("SeilaplanDialog", "m"))
        self.fieldGravSK.setItemText(0, _translate("SeilaplanDialog", "ja"))
        self.fieldGravSK.setItemText(1, _translate("SeilaplanDialog", "nein"))
        self.label_67.setText(_translate("SeilaplanDialog", "<b>Gravitationsseilkran</b>"))
        self.label_66.setText(_translate("SeilaplanDialog", "<b>Bodenabstand</b>"))
        self.infoBodenabstand.setText(_translate("SeilaplanDialog", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SeilaplanDialog", "Tragesystem #2"))
        self.label_13.setText(_translate("SeilaplanDialog", "<b>Anfangspunkt</b>"))
        self.infoVerankerungA.setText(_translate("SeilaplanDialog", "?"))
        self.label_76.setText(_translate("SeilaplanDialog", "Höhe der Anfangsstütze"))
        self.label_77.setText(_translate("SeilaplanDialog", "m"))
        self.label_78.setText(_translate("SeilaplanDialog", "Länge der Verankerung"))
        self.label_79.setText(_translate("SeilaplanDialog", "m"))
        self.label_14.setText(_translate("SeilaplanDialog", "<b>Endpunkt</b>"))
        self.infoVerankerungE.setText(_translate("SeilaplanDialog", "?"))
        self.label_80.setText(_translate("SeilaplanDialog", "Höhe der Endstütze"))
        self.label_81.setText(_translate("SeilaplanDialog", "m"))
        self.label_82.setText(_translate("SeilaplanDialog", "Länge der Verankerung"))
        self.label_83.setText(_translate("SeilaplanDialog", "m"))
        self.label_12.setText(_translate("SeilaplanDialog", "Min"))
        self.label_16.setText(_translate("SeilaplanDialog", "Max"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SeilaplanDialog", "Verankerung"))
        self.label_11.setText(_translate("SeilaplanDialog", "<b>Höhe der Zwischenstützen</b>"))
        self.label_68.setText(_translate("SeilaplanDialog", "Minimaler Abstand zwischen Stützen"))
        self.label_69.setText(_translate("SeilaplanDialog", "m"))
        self.label_70.setText(_translate("SeilaplanDialog", "Horiz. Auflösung mögl. Stützenstandorte"))
        self.label_71.setText(_translate("SeilaplanDialog", "m"))
        self.label_10.setText(_translate("SeilaplanDialog", "Maximale Anzahl Zwischenstützen"))
        self.label_3.setText(_translate("SeilaplanDialog", "<b>Positionierung der Zwischenstützen</b>"))
        self.label_72.setText(_translate("SeilaplanDialog", "Minimale Stützenhöhe"))
        self.label_73.setText(_translate("SeilaplanDialog", "m"))
        self.label_5.setText(_translate("SeilaplanDialog", "Maximale Stützenhöhe"))
        self.label_74.setText(_translate("SeilaplanDialog", "m"))
        self.label_9.setText(_translate("SeilaplanDialog", "Abstufungsinterval"))
        self.label_75.setText(_translate("SeilaplanDialog", "m"))
        self.label_17.setText(_translate("SeilaplanDialog", "Künstliche Stütze ab Stützenhöhe von"))
        self.label_84.setText(_translate("SeilaplanDialog", "m"))
        self.infoStuetzen.setText(_translate("SeilaplanDialog", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SeilaplanDialog", "Zwischenstützen"))
        self.groupBox_3.setTitle(_translate("SeilaplanDialog", "Verlauf der Seillinie"))
        self.draw.setToolTip(_translate("SeilaplanDialog", "Profil in Karte zeichnen"))
        self.draw.setText(_translate("SeilaplanDialog", "zeichnen"))
        self.label_25.setText(_translate("SeilaplanDialog", "Seillinienverlauf in Karte zeichnen"))
        self.contourLyrButton.setToolTip(_translate("SeilaplanDialog", "Höhenlinien berechnen"))
        self.symA.setText(_translate("SeilaplanDialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.label_27.setText(_translate("SeilaplanDialog", "X-Koordinate"))
        self.label_28.setText(_translate("SeilaplanDialog", "Y-Koordinate"))
        self.label_29.setText(_translate("SeilaplanDialog", "Anfangspunkt"))
        self.symTxtE.setText(_translate("SeilaplanDialog", "zu definieren"))
        self.symTxtA.setText(_translate("SeilaplanDialog", "zu definieren"))
        self.label_33.setText(_translate("SeilaplanDialog", "Endpunkt"))
        self.symE.setText(_translate("SeilaplanDialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.label_2.setText(_translate("SeilaplanDialog", "Horizontaldistanz"))
        self.label_4.setText(_translate("SeilaplanDialog", "m"))
        self.buttonShowProf.setToolTip(_translate("SeilaplanDialog", "<html><head/><body><p>Höhenprofil darstellen und fixe Stützen definieren</p></body></html>"))
        self.buttonShowProf.setText(_translate("SeilaplanDialog", "Höhenprofil"))
        self.label_8.setText(_translate("SeilaplanDialog", "<html><head/><body><p><span style=\" font-style:italic;\">Erzeugte Seillinie:</span></p></body></html>"))
        self.buttonInfo.setText(_translate("SeilaplanDialog", "Info"))
        self.buttonCancel.setText(_translate("SeilaplanDialog", "Abbrechen"))
        self.btnAdjustment.setToolTip(_translate("SeilaplanDialog", "Stützenoptimierung überspringen und direkt zur manuellen Bearbeitung der Seillinie übergehen"))
        self.btnAdjustment.setText(_translate("SeilaplanDialog", "Seillinie direkt bearbeiten"))
        self.buttonRun.setToolTip(_translate("SeilaplanDialog", "Berechnung der optimalen Stützenstandorte ausführen"))
        self.buttonRun.setText(_translate("SeilaplanDialog", "Stützen optimieren"))


from . import resources_rc
