# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seilaplanDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeilaplanDialog(object):
    def setupUi(self, SeilaplanDialog):
        SeilaplanDialog.setObjectName("SeilaplanDialog")
        SeilaplanDialog.resize(598, 877)
        SeilaplanDialog.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SeilaplanDialog.setWindowIcon(icon)
        self.gridLayout_4 = QtWidgets.QGridLayout(SeilaplanDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(SeilaplanDialog)
        self.groupBox_5.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.fieldProjName = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldProjName.sizePolicy().hasHeightForWidth())
        self.fieldProjName.setSizePolicy(sizePolicy)
        self.fieldProjName.setMinimumSize(QtCore.QSize(305, 0))
        self.fieldProjName.setObjectName("fieldProjName")
        self.gridLayout.addWidget(self.fieldProjName, 0, 2, 1, 1)
        self.buttonSavePr = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSavePr.sizePolicy().hasHeightForWidth())
        self.buttonSavePr.setSizePolicy(sizePolicy)
        self.buttonSavePr.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonSavePr.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSavePr.setIcon(icon1)
        self.buttonSavePr.setIconSize(QtCore.QSize(24, 24))
        self.buttonSavePr.setAutoDefault(False)
        self.buttonSavePr.setObjectName("buttonSavePr")
        self.gridLayout.addWidget(self.buttonSavePr, 0, 4, 1, 1)
        self.buttonOpenPr = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOpenPr.sizePolicy().hasHeightForWidth())
        self.buttonOpenPr.setSizePolicy(sizePolicy)
        self.buttonOpenPr.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonOpenPr.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOpenPr.setIcon(icon2)
        self.buttonOpenPr.setIconSize(QtCore.QSize(24, 24))
        self.buttonOpenPr.setAutoDefault(False)
        self.buttonOpenPr.setObjectName("buttonOpenPr")
        self.gridLayout.addWidget(self.buttonOpenPr, 0, 5, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(SeilaplanDialog)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.fieldParamSet = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldParamSet.sizePolicy().hasHeightForWidth())
        self.fieldParamSet.setSizePolicy(sizePolicy)
        self.fieldParamSet.setMinimumSize(QtCore.QSize(220, 0))
        self.fieldParamSet.setObjectName("fieldParamSet")
        self.horizontalLayout_13.addWidget(self.fieldParamSet)
        self.buttonSaveParamset = QtWidgets.QPushButton(self.groupBox)
        self.buttonSaveParamset.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonSaveParamset.setText("")
        self.buttonSaveParamset.setIcon(icon1)
        self.buttonSaveParamset.setIconSize(QtCore.QSize(24, 24))
        self.buttonSaveParamset.setAutoDefault(False)
        self.buttonSaveParamset.setObjectName("buttonSaveParamset")
        self.horizontalLayout_13.addWidget(self.buttonSaveParamset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.fieldBabstA = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBabstA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBabstA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBabstA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBabstA.setObjectName("fieldBabstA")
        self.gridLayout_10.addWidget(self.fieldBabstA, 7, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName("label_62")
        self.gridLayout_10.addWidget(self.label_62, 6, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(24, 0))
        self.label_64.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_64.setObjectName("label_64")
        self.gridLayout_10.addWidget(self.label_64, 7, 2, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_85.sizePolicy().hasHeightForWidth())
        self.label_85.setSizePolicy(sizePolicy)
        self.label_85.setMinimumSize(QtCore.QSize(24, 0))
        self.label_85.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_85.setObjectName("label_85")
        self.gridLayout_10.addWidget(self.label_85, 2, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName("label_55")
        self.gridLayout_10.addWidget(self.label_55, 8, 0, 1, 1)
        self.fieldHMKran = QtWidgets.QLineEdit(self.tab_3)
        self.fieldHMKran.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMKran.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMKran.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMKran.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fieldHMKran.setObjectName("fieldHMKran")
        self.gridLayout_10.addWidget(self.fieldHMKran, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 2, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.tab_3)
        self.label_63.setObjectName("label_63")
        self.gridLayout_10.addWidget(self.label_63, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 1, 0, 1, 1)
        self.fieldBefA = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBefA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBefA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBefA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBefA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fieldBefA.setObjectName("fieldBefA")
        self.gridLayout_10.addWidget(self.fieldBefA, 3, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_57.setMinimumSize(QtCore.QSize(24, 0))
        self.label_57.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_57.setObjectName("label_57")
        self.gridLayout_10.addWidget(self.label_57, 8, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem2, 5, 1, 1, 1)
        self.fieldBabstE = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBabstE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBabstE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBabstE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBabstE.setObjectName("fieldBabstE")
        self.gridLayout_10.addWidget(self.fieldBabstE, 8, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setMinimumSize(QtCore.QSize(24, 0))
        self.label_59.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_59.setObjectName("label_59")
        self.gridLayout_10.addWidget(self.label_59, 3, 2, 1, 1)
        self.fieldSeilsys = QtWidgets.QComboBox(self.tab_3)
        self.fieldSeilsys.setObjectName("fieldSeilsys")
        self.fieldSeilsys.addItem("")
        self.fieldSeilsys.addItem("")
        self.gridLayout_10.addWidget(self.fieldSeilsys, 1, 1, 1, 2)
        self.fieldBefE = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBefE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBefE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBefE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBefE.setObjectName("fieldBefE")
        self.gridLayout_10.addWidget(self.fieldBefE, 4, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setObjectName("label_61")
        self.gridLayout_10.addWidget(self.label_61, 7, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setMinimumSize(QtCore.QSize(24, 0))
        self.label_56.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_56.setObjectName("label_56")
        self.gridLayout_10.addWidget(self.label_56, 4, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab_3)
        self.label_65.setObjectName("label_65")
        self.gridLayout_10.addWidget(self.label_65, 3, 0, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_66.setObjectName("label_66")
        self.gridLayout_10.addWidget(self.label_66, 5, 0, 1, 1)
        self.fieldBabstMin = QtWidgets.QLineEdit(self.tab_3)
        self.fieldBabstMin.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldBabstMin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldBabstMin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldBabstMin.setObjectName("fieldBabstMin")
        self.gridLayout_10.addWidget(self.fieldBabstMin, 6, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setMinimumSize(QtCore.QSize(24, 0))
        self.label_60.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_60.setObjectName("label_60")
        self.gridLayout_10.addWidget(self.label_60, 6, 2, 1, 1)
        self.infoBodenabstand = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBodenabstand.sizePolicy().hasHeightForWidth())
        self.infoBodenabstand.setSizePolicy(sizePolicy)
        self.infoBodenabstand.setMinimumSize(QtCore.QSize(0, 0))
        self.infoBodenabstand.setMaximumSize(QtCore.QSize(22, 22))
        self.infoBodenabstand.setAutoDefault(False)
        self.infoBodenabstand.setObjectName("infoBodenabstand")
        self.gridLayout_10.addWidget(self.infoBodenabstand, 5, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_5.sizePolicy().hasHeightForWidth())
        self.tab_5.setSizePolicy(sizePolicy)
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(40, 0))
        self.label_36.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 5, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setMinimumSize(QtCore.QSize(0, 0))
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 3, 3, 1, 1)
        self.fieldqR = QtWidgets.QLineEdit(self.tab_5)
        self.fieldqR.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldqR.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldqR.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldqR.setObjectName("fieldqR")
        self.gridLayout_8.addWidget(self.fieldqR, 6, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setMinimumSize(QtCore.QSize(40, 0))
        self.label_47.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 4, 2, 1, 1)
        self.fieldMBK = QtWidgets.QLineEdit(self.tab_5)
        self.fieldMBK.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldMBK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldMBK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldMBK.setObjectName("fieldMBK")
        self.gridLayout_8.addWidget(self.fieldMBK, 4, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 6, 0, 1, 1)
        self.fieldQ = QtWidgets.QLineEdit(self.tab_5)
        self.fieldQ.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldQ.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldQ.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldQ.setObjectName("fieldQ")
        self.gridLayout_8.addWidget(self.fieldQ, 1, 1, 1, 1)
        self.fieldqZ = QtWidgets.QLineEdit(self.tab_5)
        self.fieldqZ.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldqZ.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldqZ.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldqZ.setObjectName("fieldqZ")
        self.gridLayout_8.addWidget(self.fieldqZ, 5, 1, 1, 1)
        self.fieldA = QtWidgets.QLineEdit(self.tab_5)
        self.fieldA.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldA.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldA.setObjectName("fieldA")
        self.gridLayout_8.addWidget(self.fieldA, 3, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(40, 0))
        self.label_44.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setMinimumSize(QtCore.QSize(40, 0))
        self.label_46.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 6, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 5, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMinimumSize(QtCore.QSize(40, 0))
        self.label_49.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 2, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setMinimumSize(QtCore.QSize(40, 0))
        self.label_51.setMaximumSize(QtCore.QSize(61, 16777215))
        self.label_51.setObjectName("label_51")
        self.gridLayout_8.addWidget(self.label_51, 3, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.tab_5)
        self.label_53.setObjectName("label_53")
        self.gridLayout_8.addWidget(self.label_53, 4, 0, 1, 1)
        self.fieldQt = QtWidgets.QLineEdit(self.tab_5)
        self.fieldQt.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldQt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldQt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldQt.setObjectName("fieldQt")
        self.gridLayout_8.addWidget(self.fieldQt, 2, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fieldHMnat = QtWidgets.QLineEdit(self.tab)
        self.fieldHMnat.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMnat.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMnat.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMnat.setObjectName("fieldHMnat")
        self.gridLayout_3.addWidget(self.fieldHMnat, 6, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setMinimumSize(QtCore.QSize(24, 0))
        self.label_74.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setMinimumSize(QtCore.QSize(24, 0))
        self.label_73.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 3, 2, 1, 1)
        self.fieldHMdelta = QtWidgets.QLineEdit(self.tab)
        self.fieldHMdelta.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMdelta.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMdelta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMdelta.setObjectName("fieldHMdelta")
        self.gridLayout_3.addWidget(self.fieldHMdelta, 5, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_84.sizePolicy().hasHeightForWidth())
        self.label_84.setSizePolicy(sizePolicy)
        self.label_84.setMinimumSize(QtCore.QSize(24, 0))
        self.label_84.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_84.setObjectName("label_84")
        self.gridLayout_3.addWidget(self.label_84, 6, 2, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy)
        self.label_71.setMinimumSize(QtCore.QSize(24, 0))
        self.label_71.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 2, 2, 1, 1)
        self.fieldMinDist = QtWidgets.QLineEdit(self.tab)
        self.fieldMinDist.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldMinDist.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldMinDist.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldMinDist.setObjectName("fieldMinDist")
        self.gridLayout_3.addWidget(self.fieldMinDist, 1, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setMinimumSize(QtCore.QSize(24, 0))
        self.label_75.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 5, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 6, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setMinimumSize(QtCore.QSize(0, 0))
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 3, 0, 1, 1)
        self.fieldHMmax = QtWidgets.QLineEdit(self.tab)
        self.fieldHMmax.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMmax.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMmax.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMmax.setObjectName("fieldHMmax")
        self.gridLayout_3.addWidget(self.fieldHMmax, 4, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_70.sizePolicy().hasHeightForWidth())
        self.label_70.setSizePolicy(sizePolicy)
        self.label_70.setMinimumSize(QtCore.QSize(0, 0))
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 2, 0, 1, 1)
        self.fieldHMmin = QtWidgets.QLineEdit(self.tab)
        self.fieldHMmin.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldHMmin.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldHMmin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldHMmin.setObjectName("fieldHMmin")
        self.gridLayout_3.addWidget(self.fieldHMmin, 3, 1, 1, 1)
        self.fieldLdelta = QtWidgets.QLineEdit(self.tab)
        self.fieldLdelta.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldLdelta.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldLdelta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldLdelta.setObjectName("fieldLdelta")
        self.gridLayout_3.addWidget(self.fieldLdelta, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_69.sizePolicy().hasHeightForWidth())
        self.label_69.setSizePolicy(sizePolicy)
        self.label_69.setMinimumSize(QtCore.QSize(24, 0))
        self.label_69.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setMinimumSize(QtCore.QSize(0, 0))
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 1, 0, 1, 1)
        self.infoStuetzen = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoStuetzen.sizePolicy().hasHeightForWidth())
        self.infoStuetzen.setSizePolicy(sizePolicy)
        self.infoStuetzen.setMinimumSize(QtCore.QSize(0, 0))
        self.infoStuetzen.setMaximumSize(QtCore.QSize(22, 22))
        self.infoStuetzen.setAutoDefault(False)
        self.infoStuetzen.setObjectName("infoStuetzen")
        self.gridLayout_3.addWidget(self.infoStuetzen, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 7, 0, 1, 1)
        self.fieldminSK = QtWidgets.QLineEdit(self.tab)
        self.fieldminSK.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldminSK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldminSK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldminSK.setObjectName("fieldminSK")
        self.gridLayout_3.addWidget(self.fieldminSK, 7, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_86.sizePolicy().hasHeightForWidth())
        self.label_86.setSizePolicy(sizePolicy)
        self.label_86.setMinimumSize(QtCore.QSize(24, 0))
        self.label_86.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label_86.setObjectName("label_86")
        self.gridLayout_3.addWidget(self.label_86, 7, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem8, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem9, 3, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_77 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setMinimumSize(QtCore.QSize(0, 0))
        self.label_77.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_77.setObjectName("label_77")
        self.gridLayout_7.addWidget(self.label_77, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem10, 0, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setMinimumSize(QtCore.QSize(0, 0))
        self.label_76.setObjectName("label_76")
        self.gridLayout_7.addWidget(self.label_76, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.fieldE = QtWidgets.QLineEdit(self.tab_2)
        self.fieldE.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldE.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldE.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldE.setObjectName("fieldE")
        self.gridLayout_7.addWidget(self.fieldE, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        self.fieldSFT = QtWidgets.QLineEdit(self.tab_2)
        self.fieldSFT.setMinimumSize(QtCore.QSize(80, 0))
        self.fieldSFT.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fieldSFT.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.fieldSFT.setObjectName("fieldSFT")
        self.gridLayout_7.addWidget(self.fieldSFT, 2, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(SeilaplanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.radioRaster = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioRaster.setToolTip("")
        self.radioRaster.setObjectName("radioRaster")
        self.gridLayout_15.addWidget(self.radioRaster, 0, 0, 1, 1)
        self.radioSurveyData = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioSurveyData.setObjectName("radioSurveyData")
        self.gridLayout_15.addWidget(self.radioSurveyData, 1, 0, 1, 1)
        self.buttonRefreshRa = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRefreshRa.sizePolicy().hasHeightForWidth())
        self.buttonRefreshRa.setSizePolicy(sizePolicy)
        self.buttonRefreshRa.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonRefreshRa.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRefreshRa.setIcon(icon3)
        self.buttonRefreshRa.setIconSize(QtCore.QSize(24, 24))
        self.buttonRefreshRa.setAutoDefault(False)
        self.buttonRefreshRa.setObjectName("buttonRefreshRa")
        self.gridLayout_15.addWidget(self.buttonRefreshRa, 0, 3, 1, 1)
        self.fieldSurveyDataPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.fieldSurveyDataPath.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.fieldSurveyDataPath.setFont(font)
        self.fieldSurveyDataPath.setStyleSheet("color: rgb(136, 138, 133);")
        self.fieldSurveyDataPath.setReadOnly(True)
        self.fieldSurveyDataPath.setObjectName("fieldSurveyDataPath")
        self.gridLayout_15.addWidget(self.fieldSurveyDataPath, 1, 2, 1, 1)
        self.rasterField = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rasterField.sizePolicy().hasHeightForWidth())
        self.rasterField.setSizePolicy(sizePolicy)
        self.rasterField.setMinimumSize(QtCore.QSize(220, 0))
        self.rasterField.setObjectName("rasterField")
        self.gridLayout_15.addWidget(self.rasterField, 0, 2, 1, 1)
        self.buttonLoadSurveyData = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonLoadSurveyData.setMaximumSize(QtCore.QSize(27, 27))
        self.buttonLoadSurveyData.setText("")
        self.buttonLoadSurveyData.setIcon(icon2)
        self.buttonLoadSurveyData.setIconSize(QtCore.QSize(24, 24))
        self.buttonLoadSurveyData.setObjectName("buttonLoadSurveyData")
        self.gridLayout_15.addWidget(self.buttonLoadSurveyData, 1, 3, 1, 1)
        self.infoSurveyData = QtWidgets.QPushButton(self.groupBox_2)
        self.infoSurveyData.setMaximumSize(QtCore.QSize(22, 22))
        self.infoSurveyData.setObjectName("infoSurveyData")
        self.gridLayout_15.addWidget(self.infoSurveyData, 1, 4, 1, 1)
        self.infoRasterlayer = QtWidgets.QPushButton(self.groupBox_2)
        self.infoRasterlayer.setMaximumSize(QtCore.QSize(22, 22))
        self.infoRasterlayer.setObjectName("infoRasterlayer")
        self.gridLayout_15.addWidget(self.infoRasterlayer, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_15)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.buttonInfo = QtWidgets.QPushButton(SeilaplanDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInfo.sizePolicy().hasHeightForWidth())
        self.buttonInfo.setSizePolicy(sizePolicy)
        self.buttonInfo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.buttonInfo.setAutoDefault(False)
        self.buttonInfo.setObjectName("buttonInfo")
        self.horizontalLayout_11.addWidget(self.buttonInfo)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.buttonCancel = QtWidgets.QPushButton(SeilaplanDialog)
        self.buttonCancel.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonCancel.setAutoDefault(False)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_11.addWidget(self.buttonCancel)
        self.btnAdjustment = QtWidgets.QPushButton(SeilaplanDialog)
        self.btnAdjustment.setAutoDefault(False)
        self.btnAdjustment.setObjectName("btnAdjustment")
        self.horizontalLayout_11.addWidget(self.btnAdjustment)
        self.buttonRun = QtWidgets.QPushButton(SeilaplanDialog)
        self.buttonRun.setAutoDefault(False)
        self.buttonRun.setObjectName("buttonRun")
        self.horizontalLayout_11.addWidget(self.buttonRun)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(SeilaplanDialog)
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{    font-weight: bold;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(False)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.draw = QtWidgets.QPushButton(self.groupBox_3)
        self.draw.setAutoDefault(False)
        self.draw.setObjectName("draw")
        self.gridLayout_17.addWidget(self.draw, 0, 1, 1, 1)
        self.osmLyrButton = QtWidgets.QPushButton(self.groupBox_3)
        self.osmLyrButton.setMaximumSize(QtCore.QSize(27, 27))
        self.osmLyrButton.setToolTip("OpenStreetMap Layer laden")
        self.osmLyrButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.osmLyrButton.setIcon(icon4)
        self.osmLyrButton.setAutoDefault(False)
        self.osmLyrButton.setObjectName("osmLyrButton")
        self.gridLayout_17.addWidget(self.osmLyrButton, 0, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_17.addWidget(self.label_25, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem13, 0, 3, 1, 1)
        self.contourLyrButton = QtWidgets.QPushButton(self.groupBox_3)
        self.contourLyrButton.setMaximumSize(QtCore.QSize(27, 27))
        self.contourLyrButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/SeilaplanPlugin/gui/icons/icon_contour.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contourLyrButton.setIcon(icon5)
        self.contourLyrButton.setAutoDefault(False)
        self.contourLyrButton.setObjectName("contourLyrButton")
        self.gridLayout_17.addWidget(self.contourLyrButton, 0, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_27.setObjectName("label_27")
        self.gridLayout_18.addWidget(self.label_27, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laenge = QtWidgets.QLineEdit(self.groupBox_3)
        self.laenge.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laenge.sizePolicy().hasHeightForWidth())
        self.laenge.setSizePolicy(sizePolicy)
        self.laenge.setMinimumSize(QtCore.QSize(69, 0))
        self.laenge.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setItalic(False)
        self.laenge.setFont(font)
        self.laenge.setAutoFillBackground(False)
        self.laenge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laenge.setReadOnly(True)
        self.laenge.setObjectName("laenge")
        self.horizontalLayout_2.addWidget(self.laenge)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(17, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.gridLayout_18.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem14, 3, 0, 1, 1)
        self.symE = QtWidgets.QLabel(self.groupBox_3)
        self.symE.setAlignment(QtCore.Qt.AlignCenter)
        self.symE.setObjectName("symE")
        self.gridLayout_18.addWidget(self.symE, 2, 3, 1, 1)
        self.fieldTypeA = QtWidgets.QComboBox(self.groupBox_3)
        self.fieldTypeA.setMinimumSize(QtCore.QSize(150, 0))
        self.fieldTypeA.setObjectName("fieldTypeA")
        self.fieldTypeA.addItem("")
        self.fieldTypeA.addItem("")
        self.fieldTypeA.addItem("")
        self.gridLayout_18.addWidget(self.fieldTypeA, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.gridLayout_18.addWidget(self.label_13, 0, 5, 1, 1)
        self.fieldTypeE = QtWidgets.QComboBox(self.groupBox_3)
        self.fieldTypeE.setMinimumSize(QtCore.QSize(150, 0))
        self.fieldTypeE.setObjectName("fieldTypeE")
        self.fieldTypeE.addItem("")
        self.fieldTypeE.addItem("")
        self.gridLayout_18.addWidget(self.fieldTypeE, 2, 5, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setMinimumSize(QtCore.QSize(130, 0))
        self.label_29.setWordWrap(False)
        self.label_29.setObjectName("label_29")
        self.gridLayout_18.addWidget(self.label_29, 1, 0, 1, 1)
        self.coordEy = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordEy.sizePolicy().hasHeightForWidth())
        self.coordEy.setSizePolicy(sizePolicy)
        self.coordEy.setMinimumSize(QtCore.QSize(80, 0))
        self.coordEy.setMaximumSize(QtCore.QSize(100, 16777215))
        self.coordEy.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordEy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordEy.setObjectName("coordEy")
        self.gridLayout_18.addWidget(self.coordEy, 2, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_18.addWidget(self.label_2, 4, 0, 1, 1)
        self.coordAy = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordAy.sizePolicy().hasHeightForWidth())
        self.coordAy.setSizePolicy(sizePolicy)
        self.coordAy.setMinimumSize(QtCore.QSize(80, 0))
        self.coordAy.setMaximumSize(QtCore.QSize(100, 16777215))
        self.coordAy.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordAy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordAy.setObjectName("coordAy")
        self.gridLayout_18.addWidget(self.coordAy, 1, 2, 1, 1)
        self.buttonShowProf = QtWidgets.QPushButton(self.groupBox_3)
        self.buttonShowProf.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonShowProf.setAutoDefault(False)
        self.buttonShowProf.setObjectName("buttonShowProf")
        self.gridLayout_18.addWidget(self.buttonShowProf, 4, 2, 1, 2)
        self.coordAx = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordAx.sizePolicy().hasHeightForWidth())
        self.coordAx.setSizePolicy(sizePolicy)
        self.coordAx.setMinimumSize(QtCore.QSize(80, 0))
        self.coordAx.setMaximumSize(QtCore.QSize(100, 16777215))
        self.coordAx.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordAx.setToolTip("")
        self.coordAx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordAx.setObjectName("coordAx")
        self.gridLayout_18.addWidget(self.coordAx, 1, 1, 1, 1)
        self.coordEx = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordEx.sizePolicy().hasHeightForWidth())
        self.coordEx.setSizePolicy(sizePolicy)
        self.coordEx.setMinimumSize(QtCore.QSize(80, 0))
        self.coordEx.setMaximumSize(QtCore.QSize(100, 16777215))
        self.coordEx.setSizeIncrement(QtCore.QSize(0, 0))
        self.coordEx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coordEx.setObjectName("coordEx")
        self.gridLayout_18.addWidget(self.coordEx, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_28.setObjectName("label_28")
        self.gridLayout_18.addWidget(self.label_28, 0, 2, 1, 1)
        self.symA = QtWidgets.QLabel(self.groupBox_3)
        self.symA.setAlignment(QtCore.Qt.AlignCenter)
        self.symA.setObjectName("symA")
        self.gridLayout_18.addWidget(self.symA, 1, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem15, 2, 6, 1, 1)
        self.infoPointE = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoPointE.sizePolicy().hasHeightForWidth())
        self.infoPointE.setSizePolicy(sizePolicy)
        self.infoPointE.setMinimumSize(QtCore.QSize(0, 0))
        self.infoPointE.setMaximumSize(QtCore.QSize(22, 22))
        self.infoPointE.setAutoDefault(False)
        self.infoPointE.setObjectName("infoPointE")
        self.gridLayout_18.addWidget(self.infoPointE, 2, 7, 1, 1)
        self.infoPointA = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoPointA.sizePolicy().hasHeightForWidth())
        self.infoPointA.setSizePolicy(sizePolicy)
        self.infoPointA.setMinimumSize(QtCore.QSize(0, 0))
        self.infoPointA.setMaximumSize(QtCore.QSize(22, 22))
        self.infoPointA.setAutoDefault(False)
        self.infoPointA.setObjectName("infoPointA")
        self.gridLayout_18.addWidget(self.infoPointA, 1, 7, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(5, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem16, 0, 7, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem17, 2, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_18, 6, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(SeilaplanDialog)
        self.tabWidget.setCurrentIndex(0)
        self.fieldSeilsys.setCurrentIndex(-1)
        self.fieldTypeA.setCurrentIndex(-1)
        self.fieldTypeE.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SeilaplanDialog)
        SeilaplanDialog.setTabOrder(self.fieldProjName, self.buttonSavePr)
        SeilaplanDialog.setTabOrder(self.buttonSavePr, self.buttonOpenPr)
        SeilaplanDialog.setTabOrder(self.buttonOpenPr, self.draw)
        SeilaplanDialog.setTabOrder(self.draw, self.fieldParamSet)
        SeilaplanDialog.setTabOrder(self.fieldParamSet, self.buttonSaveParamset)
        SeilaplanDialog.setTabOrder(self.buttonSaveParamset, self.tabWidget)
        SeilaplanDialog.setTabOrder(self.tabWidget, self.fieldQ)
        SeilaplanDialog.setTabOrder(self.fieldQ, self.fieldQt)
        SeilaplanDialog.setTabOrder(self.fieldQt, self.fieldA)
        SeilaplanDialog.setTabOrder(self.fieldA, self.fieldMBK)
        SeilaplanDialog.setTabOrder(self.fieldMBK, self.fieldqZ)
        SeilaplanDialog.setTabOrder(self.fieldqZ, self.fieldqR)
        SeilaplanDialog.setTabOrder(self.fieldqR, self.fieldE)
        SeilaplanDialog.setTabOrder(self.fieldE, self.fieldMinDist)
        SeilaplanDialog.setTabOrder(self.fieldMinDist, self.fieldLdelta)
        SeilaplanDialog.setTabOrder(self.fieldLdelta, self.buttonInfo)
        SeilaplanDialog.setTabOrder(self.buttonInfo, self.buttonCancel)
        SeilaplanDialog.setTabOrder(self.buttonCancel, self.buttonRun)

    def retranslateUi(self, SeilaplanDialog):
        _translate = QtCore.QCoreApplication.translate
        SeilaplanDialog.setWindowTitle(_translate("SeilaplanDialog", "SEILAPLAN - Seilkran-Layoutplaner"))
        self.groupBox_5.setTitle(_translate("SeilaplanDialog", "Projekt"))
        self.label_7.setText(_translate("SeilaplanDialog", "Projektname"))
        self.buttonSavePr.setToolTip(_translate("SeilaplanDialog", "Einstellungen in Textdatei abspeichern"))
        self.buttonOpenPr.setToolTip(_translate("SeilaplanDialog", "Projekteinstellungen aus Textdatei laden"))
        self.groupBox.setTitle(_translate("SeilaplanDialog", "Eigenschaften der Seillinie"))
        self.label_6.setText(_translate("SeilaplanDialog", "Parameterset auswählen"))
        self.buttonSaveParamset.setToolTip(_translate("SeilaplanDialog", "Eigenschaften der Seillinie in neuem Parameterset abspeichern"))
        self.label_62.setText(_translate("SeilaplanDialog", "Minimaler Abstand Tragseil - Boden"))
        self.label_64.setText(_translate("SeilaplanDialog", "m"))
        self.label_85.setText(_translate("SeilaplanDialog", "m"))
        self.label_55.setText(_translate("SeilaplanDialog", "einzuhalten bis ... vor dem Endpunkt"))
        self.label.setText(_translate("SeilaplanDialog", "Höhe Seilkranmast"))
        self.label_63.setText(_translate("SeilaplanDialog", "Seillinie befahrbar bis ... vor dem Endpunkt   "))
        self.label_15.setText(_translate("SeilaplanDialog", "Seilsystem"))
        self.label_57.setText(_translate("SeilaplanDialog", "m"))
        self.label_59.setText(_translate("SeilaplanDialog", "m"))
        self.fieldSeilsys.setItemText(0, _translate("SeilaplanDialog", "Zweiseil-System"))
        self.fieldSeilsys.setItemText(1, _translate("SeilaplanDialog", "Mehrseil-System"))
        self.label_61.setText(_translate("SeilaplanDialog", "einzuhalten ab ... vom Anfangspunkt"))
        self.label_56.setText(_translate("SeilaplanDialog", "m"))
        self.label_65.setText(_translate("SeilaplanDialog", "Seillinie befahrbar ab ... vom Anfangspunkt"))
        self.label_66.setText(_translate("SeilaplanDialog", "Bodenabstand"))
        self.label_60.setText(_translate("SeilaplanDialog", "m"))
        self.infoBodenabstand.setText(_translate("SeilaplanDialog", "?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SeilaplanDialog", "Seillinie"))
        self.label_36.setText(_translate("SeilaplanDialog", "kN/m"))
        self.label_50.setText(_translate("SeilaplanDialog", "Gewicht der Last inkl. Laufwagen"))
        self.label_47.setText(_translate("SeilaplanDialog", "kN"))
        self.label_35.setText(_translate("SeilaplanDialog", "Gewicht Rückholseil"))
        self.label_44.setText(_translate("SeilaplanDialog", "kN"))
        self.label_46.setText(_translate("SeilaplanDialog", "kN/m"))
        self.label_43.setText(_translate("SeilaplanDialog", "Gewicht Zugseil"))
        self.label_30.setText(_translate("SeilaplanDialog", "Querschnittsfläche Tragseil"))
        self.label_48.setText(_translate("SeilaplanDialog", "Gewicht Tragseil"))
        self.label_49.setText(_translate("SeilaplanDialog", "kN/m"))
        self.label_51.setText(_translate("SeilaplanDialog", "mm2"))
        self.label_53.setText(_translate("SeilaplanDialog", "Mindestbruchkraft Tragseil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("SeilaplanDialog", "Maschinendaten"))
        self.label_17.setText(_translate("SeilaplanDialog", "Künstliche Stütze ab Stützenhöhe von"))
        self.label_74.setText(_translate("SeilaplanDialog", "m"))
        self.label_5.setText(_translate("SeilaplanDialog", "Maximale Stützenhöhe"))
        self.label_73.setText(_translate("SeilaplanDialog", "m"))
        self.label_84.setText(_translate("SeilaplanDialog", "m"))
        self.label_71.setText(_translate("SeilaplanDialog", "m"))
        self.label_75.setText(_translate("SeilaplanDialog", "m"))
        self.label_72.setText(_translate("SeilaplanDialog", "Minimale Stützenhöhe"))
        self.label_70.setText(_translate("SeilaplanDialog", "Horiz. Auflösung mögl. Stützenstandorte"))
        self.label_9.setText(_translate("SeilaplanDialog", "Abstufungsinterval"))
        self.label_69.setText(_translate("SeilaplanDialog", "m"))
        self.label_3.setText(_translate("SeilaplanDialog", "Optimierungsparameter"))
        self.label_68.setText(_translate("SeilaplanDialog", "Minimaler Abstand zwischen Stützen"))
        self.infoStuetzen.setText(_translate("SeilaplanDialog", "?"))
        self.label_14.setText(_translate("SeilaplanDialog", "Minimal gewählte Seilzugkraft"))
        self.label_86.setText(_translate("SeilaplanDialog", "kN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SeilaplanDialog", "Optional #1"))
        self.label_77.setText(_translate("SeilaplanDialog", "kN/mm2"))
        self.label_76.setText(_translate("SeilaplanDialog", "Elastizitätsmodul Tragseil"))
        self.label_11.setText(_translate("SeilaplanDialog", "Diverses"))
        self.label_12.setText(_translate("SeilaplanDialog", "Sicherheitsfaktor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SeilaplanDialog", "Optional #2"))
        self.groupBox_2.setTitle(_translate("SeilaplanDialog", "Höhenmodell"))
        self.radioRaster.setText(_translate("SeilaplanDialog", "Rasterlayer"))
        self.radioSurveyData.setText(_translate("SeilaplanDialog", "Geländeprofil"))
        self.buttonRefreshRa.setToolTip(_translate("SeilaplanDialog", "Liste der in QGIS geladenen Raster aktualisieren"))
        self.fieldSurveyDataPath.setToolTip(_translate("SeilaplanDialog", "Pfad zu csv-Datei"))
        self.buttonLoadSurveyData.setToolTip(_translate("SeilaplanDialog", "Öffne Komma-getrennte Textdatei (.csv Datei)"))
        self.infoSurveyData.setText(_translate("SeilaplanDialog", "?"))
        self.infoRasterlayer.setText(_translate("SeilaplanDialog", "?"))
        self.buttonInfo.setText(_translate("SeilaplanDialog", "Info"))
        self.buttonCancel.setText(_translate("SeilaplanDialog", "Abbrechen"))
        self.btnAdjustment.setToolTip(_translate("SeilaplanDialog", "Stützenoptimierung überspringen und direkt zur manuellen Bearbeitung der Seillinie übergehen"))
        self.btnAdjustment.setText(_translate("SeilaplanDialog", "Seillinie direkt bearbeiten"))
        self.buttonRun.setToolTip(_translate("SeilaplanDialog", "Berechnung der optimalen Stützenstandorte ausführen"))
        self.buttonRun.setText(_translate("SeilaplanDialog", "Stützen optimieren"))
        self.groupBox_3.setTitle(_translate("SeilaplanDialog", "Verlauf der Seillinie"))
        self.label_8.setText(_translate("SeilaplanDialog", "oder Koordinaten der Seillinie manuell angeben:"))
        self.draw.setToolTip(_translate("SeilaplanDialog", "Profil in Karte zeichnen"))
        self.draw.setText(_translate("SeilaplanDialog", "zeichnen"))
        self.label_25.setText(_translate("SeilaplanDialog", "Seillinie in Karte einzeichnen"))
        self.contourLyrButton.setToolTip(_translate("SeilaplanDialog", "Höhenlinien darstellen"))
        self.label_27.setText(_translate("SeilaplanDialog", "X-Koordinate"))
        self.label_4.setText(_translate("SeilaplanDialog", "m"))
        self.symE.setText(_translate("SeilaplanDialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.fieldTypeA.setItemText(0, _translate("SeilaplanDialog", "Stütze"))
        self.fieldTypeA.setItemText(1, _translate("SeilaplanDialog", "Verankerung"))
        self.fieldTypeA.setItemText(2, _translate("SeilaplanDialog", "Seilkran"))
        self.label_13.setText(_translate("SeilaplanDialog", "Punktart"))
        self.fieldTypeE.setItemText(0, _translate("SeilaplanDialog", "Stütze"))
        self.fieldTypeE.setItemText(1, _translate("SeilaplanDialog", "Verankerung"))
        self.label_29.setText(_translate("SeilaplanDialog", "<html><head/><body>Anfangspunkt<br><span style=\" font-size:9pt;\">(bei Maschine/Winde)</span></body></html>"))
        self.label_33.setText(_translate("SeilaplanDialog", "Endpunkt"))
        self.label_2.setText(_translate("SeilaplanDialog", "Horizontaldistanz"))
        self.buttonShowProf.setToolTip(_translate("SeilaplanDialog", "Geländelinie in Diagramm darstellen und fixe Stützen definieren"))
        self.buttonShowProf.setText(_translate("SeilaplanDialog", "Geländelinie"))
        self.label_28.setText(_translate("SeilaplanDialog", "Y-Koordinate"))
        self.symA.setText(_translate("SeilaplanDialog", "<html><head/><body><p><img src=\":/plugins/SeilaplanPlugin/gui/icons/icon_yellow.png\"/></p></body></html>"))
        self.infoPointE.setText(_translate("SeilaplanDialog", "?"))
        self.infoPointA.setText(_translate("SeilaplanDialog", "?"))


from . import resources_rc
